[project]
name = "fptest1"
version = "0.1.0"
description = "Erstes Testrepo für FP Blockpraktikum"
readme = "README.md"
authors = [
    { name = "Felix Gloistein", email = "felixgloistein@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pre-commit>=4.6.2",
    "qiskit-aer>=0.17.2",
    "qiskit[visualization]>=2.5.2",
]

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[tool.ruff.lint]
extend-select = ["NPY"]
